### ISSUE TITLE
"inspired by diu"

### ISSUE THREAD

**Issue by faetalize** [babaohuang/GeminiProChat#5]
this project is plagiarism you took https://chatgpt.ddiu.me/ & https://github.com/anse-app/chatgpt-demo and just changed a couple of words in the html? even the github issues in this repo lead to https://github.com/anse-app/chatgpt-demo/discussions

you can't even say you're within the bounds of the MIT license because you removed mentions to it and added a GPL instead..?

**Comment by babaohuang** [comment]
Dear [faetalize](https://github.com/faetalize),

I want to sincerely apologize for the issues you've pointed out regarding my GitHub project. After reading your comment, I've realized that I made a significant oversight in regards to the licensing and attribution of the original projects [https://chatgpt.ddiu.me/](https://chatgpt.ddiu.me/) and [https://github.com/anse-app/chatgpt-demo](https://github.com/anse-app/chatgpt-demo).

Firstly, I acknowledge my mistake in changing the license from MIT to GPL. This was not done with the intent to disregard the original licensing terms, but rather due to a lack of understanding on my part.I have already reverted the license back to MIT to respect the original creators' terms.

Additionally, I have been focused on bug fixes and updates, which led to a delay in updating the README file. However, I realize the importance of proper attribution and giving credit where it's due. I am immediately updating the README file to clearly state the original sources and their contributions.

I assure you that this was not an act of intentional plagiarism or disrespect. I failed to give the required attention to licensing and attribution details in my eagerness to release the project. I am committed to rectifying these mistakes and ensuring that my project adheres to the correct open-source standards.

Thank you for bringing this to my attention. I am grateful for the opportunity to learn from this experience and to correct my errors. Your feedback is invaluable to maintaining the integrity and collaborative spirit of the open-source community.

Best regards,
babaohuang

**Comment by faetalize** [comment]
If you're going to actually do those things, then sweet.

However you really used AI to generate your reply? Wild

**Comment by babaohuang** [comment]
> If you're going to actually do those things, then sweet.如果你真的打算去做那些事情，那太好了。
> 
> However you really used AI to generate your reply? Wild然而你真的使用了人工智能来生成你的回复吗？疯狂

Indeed, I used GPT to refine my response. I wanted to ensure my message was clear and respectful.

**Comment by faetalize** [comment]
Thank yoou
